### ISSUE TITLE
 [Re] Inter-areal balanced amplification enhances signal propagation in a large-scale circuit model of the primate cortex

### ISSUE THREAD

**Issue by ViniciusLima94** [ReScience/submissions#72] opened 2023-05-05 14:05 UTC
**Original article:** Joglekar, Madhura R., et al. "Inter-areal balanced amplification enhances signal propagation in a large-scale circuit model of the primate cortex." Neuron 98.1 (2018): 222-234.

**PDF URL:**  https://github.com/ViniciusLima94/ReScience-Joglekar/blob/master/ReScience_Joglekar.pdf
**Metadata URL:** https://github.com/ViniciusLima94/ReScience-Joglekar/blob/master/metadata.tex
**Code URL:**  https://github.com/ViniciusLima94/ReScience-Joglekar/tree/master/code

**Scientific domain:** Computational Neuroscience
**Programming language:**  Python (NEST SIMULATOR)
**Suggested editor:** @rougier 
**Suggested reviewers:** Hans Ekkehard Plesser, Robin Gutzen, Vahid Rostami, Marcel Stimberg

**Comment by rougier** [comment] 2023-05-12 15:29
Thanks for your submission, we'll assign an editor soon!

**Comment by rougier** [comment] 2023-05-12 15:30
@benoit-girard @oliviaguest Can any of you edit this submission ?

**Comment by oliviaguest** [comment] 2023-05-16 15:44
@rougier this is really outside my expertise, sorry!

**Comment by benoit-girard** [comment] 2023-05-28 15:18
I will handle this one.

**Comment by benoit-girard** [comment] 2023-05-28 15:43
Dear @ViniciusLima94 the provided URLs end-up on "error 404", can you do something about that?

**Comment by ViniciusLima94** [comment] 2023-05-30 07:58
Dear @benoit-girard , I believe that was because I forgot to change the repository to public.

It should work now, can you let me know?

Thank you.

**Comment by benoit-girard** [comment] 2023-05-31 15:50
@ViniciusLima94 I can now access it, thanks.
I now will be looking for reviewers!

**Comment by ViniciusLima94** [comment] 2023-05-31 16:10
Thank you @benoit-girard !

**Comment by benoit-girard** [comment] 2023-06-05 08:22
@damiendr and @rgutzen : would you be interested (and available) to review this submission to ReScience C?

**Comment by rgutzen** [comment] 2023-06-05 09:03
I have a potential conflict of interest since I'm currently working in the same lab as the second first author Renan Shimoura.

**Comment by benoit-girard** [comment] 2023-06-08 07:58
@rgutzen thanks for your answer, I will then contact someone else.

**Comment by benoit-girard** [comment] 2023-06-08 10:03
@mstimberg : would you be interested (and available) to review this submission to ReScience C?

**Comment by mstimberg** [comment] 2023-06-09 15:35
@benoit-girard : yes, would be happy to review it :blush:

**Comment by benoit-girard** [comment] 2023-06-09 16:15
Great, thanks Marcel!

**Comment by mstimberg** [comment] 2023-06-21 10:16
@benoit-girard a quick question (it's been a while since I reviewed for ReScience…): should I go ahead with my review, or wait until a second reviewer is assigned?

**Comment by benoit-girard** [comment] 2023-06-22 08:29
Sorry, I should have been explicit about that: yes, you can go ahead. 
I will try to identify a 2nd reviewer as fast as possible.

**Comment by benoit-girard** [comment] 2023-06-22 08:33
@heplesser : would you be interested and available to review this paper?

**Comment by heplesser** [comment] 2023-06-22 12:41
I am afraid I would not get around to reviewing before August.

**Comment by benoit-girard** [comment] 2023-06-23 10:57
@heplesser : I will try to find someone that can work on it in the coming week, but should I fail, I may come back to you in August...

**Comment by benoit-girard** [comment] 2023-06-23 10:57
@otizonaizit : would you be interested and available to review this paper?

**Comment by mstimberg** [comment] 2023-07-03 14:05
:wave: @ViniciusLima94, @benoit-girard, please find my review below:

I have reviewed the paper/code and can confirm that the code reproduces the figures of the ReScience manuscript. I can also confirm that these results replicate the results from the original paper (within reasonable bounds). In general, this is a well executed replication, the paper is clearly written and convincingly discusses the issues encountered during the replication. The availability of the source code for the original paper remains a bit unclear to me (see below). This and missing instructions in the code repository are the major issues that IMHO should be addressed before publication. I also identified a number of minor issues, see the list below

### Major issues
- **Availability of original source code:** Most of the ReScience manuscript reads as if the Brian 2 source code of the original paper is not available (it does not seem to be linked from the original article), and the authors therefore had to write the NEST implementation from scratch based on the description in the paper (and guessing/adjusting a few parameters that weren't explicitly mentioned). But then I was confused by the comment on p.12: "Furthermore, we noticed the same phenomenon when running the original Brian 2 code for this model (data not shown)." Does that mean that the authors had access to the original Brian 2 code, e.g. by asking the authors for it? If yes, why did this not clear up the questions of the unspecified parameters? In either case, I think the (un)availability of the original source code should be stated near the beginning of the manuscript, possibly mentioning the unreferenced Matlab code that the authors found on GitHub as well.
- **Installation/run instructions**: The code repository currently does not contain any README file or other explication on how to install the necessary requirements and to run the code. Everything is rather straightforward (conda environment, `main.py` file that can run the various protocols, etc.), but there should be step-by-step instructions how to install and run everything. The authors provide two conda environments, one with detailed pinned versions (which I used) and one which only states the general dependencies. I think the latter needs to specify that the NEST versions needs to be at least version 3.0 which integrates the adapted rate model. The authors state that "it is recommended to use this updated version", but I think it is not only "recommended" but necessary to run the code?
  If I am not mistaken, NEST simulations are only reproducible by fixing both the seed and the number of threads used for simulation. This should be made explicit in the instructions as well.

### Minor issues
#### Paper
- p.1: "Here we replicate a recent modelling by" → "a recent modelling **study** by"
- p.1: "One of the key contributions Joglekar et. al. study"  → "**of** the Joglekar et al. study" (also in several places: "et. al." should be "et al.")
- p.2: "with the code related to this article in: XXXXXX" needs a URL
- Figure 1: I'd again state here what "FLN" stands for, since someone might look at the figure before reading the rest of the text. Also, you might consider plotting FLN instead of log(FLN) and use a logarithmic color map, so that the colorbar values would be 10², 10⁴, etc. A bit clearer IMO, but of course there's nothing wrong with the current figure.
- Figure 3f: The legend in the figure seems to have swapped the labels for the dotted vs. solid lines
- References: Readers would appreciate DOIs for the references, I think
#### Code
- Even after looking at the source code, I am not quite what "protocol 3" does. The comment states "compute average frequencies per population in each stage", but there does not seem to be any output/figure at the end of the simulation
- "protocol 4" is an option in `main.py` but does not do anything
- The generated file names 5, 6, 7 correspond to figures 4, 5, 6 in the paper, which is a bit confusing
- One of the generated files has "joglekar" in the name (`fig3_joglekar_e`) while all the others are simply called `fig_3f`, etc.

**Comment by benoit-girard** [comment] 2023-07-04 07:45
@vitay @stephanmg @pietromarchesi : would one of you be available to provide a second review of this submission?

**Comment by benoit-girard** [comment] 2023-07-04 07:47
@mstimberg : thanks a lot for the review!

**Comment by benoit-girard** [comment] 2023-07-04 07:48
@ViniciusLima94 : you can start adressing the points raised by @mstimberg while I continue to search for a second reviewer.

**Comment by ViniciusLima94** [comment] 2023-07-04 07:51
Thank you very much for you review and commends on our manuscript @mstimberg . I'll start to address the points raised as soon as possible, @benoit-girard .

**Comment by stephanmg** [comment] 2023-07-04 07:55
> @vitay @stephanmg @pietromarchesi : would one of you be available to provide a second review of this submission?

Hi @benoit-girard, I would like to do a review for this submission.

**Comment by benoit-girard** [comment] 2023-07-04 08:54
This is great, @stephanmg, thanks a lot! You are welcome to proceed!

**Comment by ViniciusLima94** [comment] 2023-07-11 14:46
Dear @mstimberg ,

We thank you for reviewing our manuscript, and for the suggestions and corrections that you suggest. As it is usual, changes in the manuscript will be indicated with blue text, and bellow we list your comments followed by our responses.

### Major issues

> **Availability of original source code: Most of the ReScience manuscript reads as if the Brian 2 source code of the original paper is not available (it does not seem to be linked from the original article), and the authors therefore had to write the NEST implementation from scratch based on the description in the paper (and guessing/adjusting a few parameters that weren't explicitly mentioned). But then I was confused by the comment on p.12: "Furthermore, we noticed the same phenomenon when running the original Brian 2 code for this model (data not shown)." Does that mean that the authors had access to the original Brian 2 code, e.g. by asking the authors for it? If yes, why did this not clear up the questions of the unspecified parameters? In either case, I think the (un)availability of the original source code should be stated near the beginning of the manuscript, possibly mentioning the unreferenced Matlab code that the authors found on GitHub as well.**

We thank the reviewer for pointing out our lack of clarity regarding the presence of Brian 2 source code associated with the original publication and its use in replicating the results.

We added a section right after the paper’s Introduction named “Availability of code implementations for the original model”, clarifying this issue:

_In the original publication, the authors do not link any associated code repository with their implementation of the models described. However, we found a repository with Matlab and Python (Brian 2) scripts in the following address:  \href{github.com/xjwanglab/JoglekarEtAl2018_Neuron}{github.com/xjwanglab/JoglekarEtAl2018_Neuron}. Despite the fact that those scripts helped to detect discrepancies and non-specified parameters in the original article, for the spiking model, not all parameters could be directly ``plugged-in'' into Nest without conversion, and some adjustment was often required in order to obtain the firing rate regimes specified in the original paper, as we elaborated throughout this replication paper._

In the results section we modified the following two descriptions to make it clear how exactly the authors’ implementation helped us to replicate the model.

Paragraph after equation 27:
_This condition was not mentioned in the original article. However it was found in the Matlab implementation of the model that we cited in the section ``Availability of code implementations for the original model''._

Paragraph after equation 28:
_In the original paper, the authors mention that a background input was given to the network in order to maintain the spiking activity of the excitatory population between $0.75$ and $1.5$ Hz and the inhibitory population between $5$ and$6$ Hz. Although the authors did not specify the background noise parameters, the model equations found in their Brian2 code take the form $dV/dt = f(V) + (\sigma/\tau)\xi(t)$ (``rishimodelpython_brian2_spiking.py''), lines 137 and 141). We converted the values of $\sigma$ set on their code using Eq.ref{eq:noise_input}. However, some adjustments of the parameters were required to reproduce the specified steady-state rates (Table~ref{tab:rates})._

Text added in section 3.3, subsection “Synchronous regime”:
_Furthermore, we noticed the same phenomenon  when running the original Brian 2 code for this model (data not shown), which suggests this is not an issue of incorrectly fitting parameters but rather an intrinsic property of the model. Additionally, we noticed that in the authors' script the seed was fixed (``rishimodelpython_brian2_spiking.py'', lines 30-32)._


> Installation/run instructions: The code repository currently does not contain any README file or other explanation on how to install the necessary requirements and to run the code. Everything is rather straightforward (conda environment, main.py file that can run the various protocols, etc.), but there should be step-by-step instructions on how to install and run everything. The authors provide two conda environments, one with detailed pinned versions (which I used) and one which only states the general dependencies. I think the latter needs to specify that the NEST version needs to be at least version 3.0 which integrates the adapted rate model. The authors state that "it is recommended to use this updated version", but I think it is not only "recommended" but necessary to run the code?
    If I am not mistaken, NEST simulations are only reproducible by fixing both the seed and the number of threads used for simulation. This should be made explicit in the instructions as well.


We thank the reviewer for pointing out our mistake. We now added a detailed README file to the code directory.

### Minor issues

#### Paper

> p.1: "Here we replicate a recent modelling by" → "a recent modelling study by"

We thank the reviewer for pointing out our mistake. The sentence is now corrected.

> p.1: "One of the key contributions Joglekar et. al. study" → "of the Joglekar et al. study" (also in several places: "et. al." should be "et al.")

We thank the reviewer for pointing out our mistake. The sentence is now corrected.

> p.2: "with the code related to this article in: XXXXXX" needs a URL

We thank the reviewer for pointing out our mistake. We have now inserted the link to the following repository: github.com/ViniciusLima94/ReScience-Joglekar/blob/master/code/interareal/

> Figure 1: I'd again state here what "FLN" stands for, since someone might look at the figure before reading the rest of the text. Also, you might consider plotting FLN instead of log(FLN) and use a logarithmic color map, so that the colorbar values would be 10², 10⁴, etc. A bit clearer IMO, but of course there's nothing wrong with the current figure.

We thank the reviewer for the suggestion, we have updated the Figure 1(a), by showing FLN rather than log(FLN), and adopted a logarithmic scale for the colorbar. Additionally, we replaced the title “log(FLN)” in this panel by “Connection strength”.

> Figure 3f: The legend in the figure seems to have swapped the labels for the dotted vs. solid lines

We thank the reviewer for directing our attention to this mistake. We have now corrected it.

> References: Readers would appreciate DOIs for the references, I think

We added the DOIs to the references in the bibtex file however they still do not appear in the paper. 

#### Code

> Even after looking at the source code, I am not quite sure what "protocol 3" does. The comment states "compute average frequencies per population in each stage", but there does not seem to be any output/figure at the end of the simulation

We thank the reviewer for directing our attention to this mistake. Indeed, there is no output figure for this protocol since it serves to compute the neurons’ population average firing rate to verify if they lie in the ranges specified by the original paper, as we mention in Section 3.4:

“were the mean firing rate ranges in the absence of input which are: 0.75 to 1.5 Hz for the excitatory population; and 5 to 6 Hz for the inhibitory population.”

The outcomes of this protocol are shown in Table 4.

Additionally, we added the following print commands at the end of protocol 3 (lines 210-218 on main.py):

print(f" Weak GBA ")
print(f" | Async | Sync |")
print(f" E | {rewa}| {rews}|")
print(f" I | {riwa}| {riws}|")
print("------------------------------")
print(f" Strong GBA ")
print(f" | Async | Sync |")
print(f" E | {resa}| {ress}|")
print(f" I | {risa}| {riss}|") 

Which will give the average firing rate as values printed in the command line.

> "protocol 4" is an option in main.py but does not do anything

We thank the reviewer for directing our attention to this mistake. We removed protocol 4 from the argparse options.

Before we had protocol four to simulate the Synchronous regime with strong GBA in a case where the activity of the neurons diverge.

Before submission, we moved this analysis to protocol 3, and it is corresponding to the last simulation in this protocol (lines 163-164 in main.py)

i_ss, _, t_ss, _, maxf_ss,_,_ = fig5_6.simulate(lnt = lnt, seed = 10, simtime = simtime, reg = 'sync', gba = 'strong-gba', transient = 0, dt = dt) plot_figures.plot_raster(t_ss, i_ss, None, simtime, 'figures/fig7.png', save=True) 

>  The generated file names 5, 6, 7 correspond to figures 4, 5, 6 in the paper, which is a bit confusing

We thank the reviewer for directing our attention to this mistake. We have renamed the corresponding figures to match their order in the paper.

>  One of the generated files has "joglekar" in the name (fig3_joglekar_e) while all the others are simply called fig_3f, etc.

We thank the reviewer for directing our attention to this mistake. We have corrected it.

**Comment by stephanmg** [comment] 2023-07-12 13:37
> This is great, @stephanmg, thanks a lot! You are welcome to proceed!

Will provide my review by end of the next week.

**Comment by benoit-girard** [comment] 2023-07-13 14:22
@mstimberg : Are you satisfied with the authors' answers and modifications based on your review?

@stephanmg : Perfect!

**Comment by mstimberg** [comment] 2023-07-21 17:31
@benoit-girard, @ViniciusLima94
I thank the authors for the changes, almost all of my concerns have been addressed. I was able to run all the code and to reproduce all the figures (with one minor exception, see below) and table 4 following the (very detailed!) instructions in the README file. I did all this based on the conda environment, so I did not review the other installation instructions (NEST from source, pip installs, etc.) in detail, but everything seemed very reasonable from a cursory look. 
My figure 5 looks slightly different from the one in the paper, though – could this be an issue with seed and/or number of threads? I ran it with NEST 3.4 and 20 threads (`python main.py 2 20`):

![fig5](https://github.com/ReScience/submissions/assets/1381982/0d36545b-418b-4bf5-8345-4e810918ccf1)


A bit of nitpicking: `fig1_b.pdf` and `fig1_c.pdf` appear as Figure 2b and 2c in the paper :)

I am in general convinced with the explanations regarding the parameters that weren't mentioned in the original paper, but could you comment more on the $\tau$ parameter? You state that you could not find values in the code and used 20ms in the weak LBA and 30ms in the strong LBA condition, with the same values for excitatory and inhbitory cells. From a quick look at the source code in rishimodelpython_brian2_spiking.py, however, it seems that they used 20ms for excitatory and 10ms for inhibitory cells?
https://github.com/xjwanglab/JoglekarEtAl2018_Neuron/blob/42c21da0df79611f62b8aa549b2bacd921c79d61/rishimodelpython_brian2_spiking.py#L38-L39C1

> We added the DOIs to the references in the bibtex file however they still do not appear in the paper.

Um, apologies, apparently displaying them is switched off in the LaTeX template (not quite sure why?).

**Comment by stephanmg** [comment] 2023-07-24 09:40
Thanks for the submission @ViniciusLima94 

@benoit-girard find my comments below, most of the issues have been fixed meanwhile by @ViniciusLima94 though...

# Major issues

The most major issue I faced was the lack of running instructions / README. 
This seems already been fixed in a pretty detailed way now. Very good!

# Minor issues
Paper:
- Typos ("wring distance"), need to double check for them throughout manuscript
- Figure 2. Wouldn't mix red and green in a figure (color-blind)
- Would avoid highlighting in Table 2 but state in legend, same for a later Table
- Figure 2. Fonts seems rather small in legend and axis description
- DOIs are now available? In the recent manuscript I still do not see them.


Code
- Remove superfluous / unused code in main.py
- Has the code been linted? It partly looks like, but would be great to have a consistent formatting throughout. Please double check.


@mstimberg my figure looks also slightly different than yours...  I'm not too familiar with NEST simulator, but I agree it could then be an issue of seeds / number of threads perhaps. NEST 3.5 and number of threads 32 is what I used.

**Comment by mstimberg** [comment] 2023-07-24 09:52
> @mstim my figure looks also slightly different than yours... I'm not too familiar with NEST simulator, but I agree it could then be an issue of seeds / number of threads perhaps. NEST 3.5 and number of threads 32.

In the new README they state that they ran with 20 threads, which is what I used. So that might explain the differences between our results (but not the difference to the result in the manuscript). But I just realized that it also depends on the compiler that is used (see [NEST docs](https://nest-simulator.readthedocs.io/en/stable/nest_behavior/random_numbers.html)). I guess in my case (Linux, NEST installed via conda) it uses GCC, but if you or the authors are on macOS, it might rather use clang?

PS: @mstimberg, not `@mstim` :)

**Comment by stephanmg** [comment] 2023-07-24 09:58
> > @mstim my figure looks also slightly different than yours... I'm not too familiar with NEST simulator, but I agree it could then be an issue of seeds / number of threads perhaps. NEST 3.5 and number of threads 32.
> 
> In the new README they state that they ran with 20 threads, which is what I used. So that might explain the differences between our results (but not the difference to the result in the manuscript). But I just realized that it also depends on the compiler that is used (see [NEST docs](https://nest-simulator.readthedocs.io/en/stable/nest_behavior/random_numbers.html)). I guess in my case (Linux, NEST installed via conda) it uses GCC, but if you or the authors are on macOS, it might rather use clang?
> 
> PS: @mstimberg, not `@mstim` :)

Ah, that might explain it, I'm using clang on OSX. But I can also try it on my Ubuntu if necessary.

**Comment by stephanmg** [comment] 2023-07-27 08:55
To wrap it up:
I do not have further objections, if the points I raised are incorporated into the manuscript.

**Comment by ViniciusLima94** [comment] 2023-07-27 15:01
Dear @mstimberg, we thank you again for your remarks and commentaries that allowed us to improve our manuscript. We will answer your new batch of suggestions in topics bellow:

> My figure 5 looks slightly different from the one in the paper, though – could this be an issue with seed and/or number of threads? I ran it with NEST 3.4 and 20 threads (python main.py 2 20):

Thank you for bringing this issue for our attention. We were able to reproduce the same result you had above.
While we don’t have a concrete answer to why this happened, there are a few things we can comment on:

- As you mentioned, it could be an issue related to the NEST version and the C compiler it uses. 

- Since we originally run the script using the NEST 3 version, and the environment uses NEST 3.4, the RNG generator could have changed.

- We noticed that by slightly decreasing the inhibition component of the drive currents for the synchronous regime network we could retrieve the original result (running with python main.py 2 20). The new version of the code we pushed has the updated parameter (line 133 of setParams.py). The new values were updated in table 2 of the manuscript.

But in any case, we do confirm that it will depend on the number of threads (seeds set) :

![image](https://github.com/ReScience/submissions/assets/17538901/ad3d0af4-dc2a-40f3-b4ad-cf4927300355)

At the same time, the result in Figure 6, portraying the instability of the network in this regime does not show an unstable firing rate anymore. We could find an unstable state again when using the seed 100 (line 227-235 in main.py) and by running the script with four threads: python main.py 2 4. We tested it in different laptops using the conda environment we provided. 

In the new version of the manuscript we added a comment (see section Important information needed during replication) that the results, for instance to each extent the stimulus will propagate and whether the firing rate will be stable, depends on the version of NEST and Python as well as the number of threads used. We comment this on the results section for the synchronous spiking neuronal model:

_“Conversely, this dependence on initial conditions can generate instances in which the network is in a less excitable state, as a consequence activity may not reach areas such as PROm. In other cases, activity will reach even area 24c, without divergence of firing rates, if the network is in a slightly more excitable state.”_

Finally, we recall that the instability effect is also observed by running their Brian 2 code for the synchronous and strong GBA regime (see Figure below obtained by running their code), hence this is not solely due to NEST.

![image](https://github.com/ReScience/submissions/assets/17538901/02ee671a-20e5-45f3-99ed-03242d4624cd)

> A bit of nitpicking: fig1_b.pdf and fig1_c.pdf appear as Figure 2b and 2c in the paper :)

True, we have changed the filename. We have also changed the name of the corresponding functions in “plot_figures.py” (fig1b() -> fig2b(); fig1c() -> fig2c()).

> I am in general convinced with the explanations regarding the parameters that weren't mentioned in the original paper, but could you comment more on the parameters? You state that you could not find values in the code and used 20ms in the weak LBA and 30ms in the strong LBA condition, with the same values for excitatory and inhibitory cells. From a quick look at the source code in rishimodelpython_brian2_spiking.py, however, it seems that they used 20ms for excitatory and 10ms for inhibitory cells?

If I’m not mistaken the missing tau I referred to is the one for the local circuit using a rate model (figure 2 in the paper; and table 2). The link above is for the spiking model, for which we used the values you mentioned (lines 62 and 63 in our setParams.py).

### Additional modifications

- To follow the numbering of figures we also rename the scripts fig1.py and fig5_6.py to fig2.py and fig4_5_6.py, respectively (the mention of those scripts in the README file were changed accordingly).
- We updated the values of $\mu_{V,E}$, $\mu_{V,I}$ in Table 5 to the correct ones.

**Comment by ViniciusLima94** [comment] 2023-07-27 15:03
Dear @stephanmg, we thank you for your remarks and commentaries that helped us to improve our ReScience manuscript.

### Paper

> Typos ("wring distance"), need to double check for them throughout manuscript

We double checked the manuscript for the mentioned typo, we found it  in the legend of figure 2 and corrected it.
	
> Figure 2. Wouldn't mix red and green in a figure (color-blind)

We  updated the colors to blue (with dashed lines), and black in the new version of the manuscript.

> Would avoid highlighting in Table 2 but state in legend, same for a later Table

We opted to keep the highlighting since it gives an immediate view of the missing parameters, but we also comment on the legends in the new version of the manuscript.

> Figure 2. Fonts seems rather small in legend and axis description

We increased the font size of labels/legends/titles to 15 points  in the new version of the manuscript.

> DOIs are now available? In the recent manuscript I still do not see them.

We managed to make DOis visible by setting “doi = true”, in line 305 of rescience.cls.

### Code

> Remove superfluous / unused code in main.py

We have removed unnecessary comments and unused code from this and other scripts.

> Has the code been linted? It partly looks like, but would be great to have a consistent formatting throughout. Please double check.

We improved the code quality by running black and manually adjusting each script where needed.

**Comment by stephanmg** [comment] 2023-07-28 09:35
LGTM now, also the reproduction issue above looks good.

**Comment by mstimberg** [comment] 2023-07-28 14:18
All looks good from my side as well, thanks for the additional explanations here and in the paper. Of course, I can't leave without some final nitpicking – but please go ahead and take these comments into account as you see fit, no need for another round of review from my side:
- In a freshly checked out repo, the `code/figures` directory does not exist and the plotting code will raise an error trying to write to that directory
- I think `fig3_b_d.pdf` should be `fig3_c_d.pdf` :smile: 
- I can reproduce Fig 4 and 5 by running `python main.py 2 20` and Fig 6 by running `python main.py 2 4` – but maybe it would be good to separate the two so that one can exactly reproduce the figures from the paper without overwriting the figures from the other call? Another option would be to give an option to call `main.py` without any number of threads, and explicitly use the thread numbers used by the authors for each plot.

All in all, great work, I was happy to review it :tada:

**Comment by ViniciusLima94** [comment] 2023-07-28 14:54
Dear @mstimberg ,

We thank you for your final remarks.

> In a freshly checked out repo, the code/figures directory does not exist and the plotting code will raise an error trying to write to that directory

We pushed the figures directory.

> I think fig3_b_d.pdf should be fig3_c_d.pdf

We updated the name of the figure to be "fig3_c_d.pdf ".

> I can reproduce Fig 4 and 5 by running python main.py 2 20 and Fig 6 by running python main.py 2 4 – but maybe it would be good to separate the two so that one can exactly reproduce the figures from the paper without overwriting the figures from the other call? Another option would be to give an option to call main.py without any number of threads, and explicitly use the thread numbers used by the authors for each plot.

Now the simulation that generates Figure 6 is in a separated protocol, we added the new protocol to the README file, where we also indicate the number of threads used to exactly reproduce the figure in our manuscript.

We thank you and @stephanmg for the comments that helped us to improve this code+manuscript considerably :)

**Comment by ViniciusLima94** [comment] 2023-08-29 13:50
Dear @benoit-girard ,

Let us know if something else is need from our part in order to proceed.

Best regards,
Vinicius.

**Comment by benoit-girard** [comment] 2023-08-29 21:24
Sorry for the delay, I am back from holidays and I can see that all of you have done a great job in the mean time!
I understand from the reviewers' last feedback that they are satisfied, so the paper is accepted, we will now proceed with the publishing steps...

**Comment by ViniciusLima94** [comment] 2023-09-07 10:19
No problem @benoit-girard .
Thank you!

**Comment by benoit-girard** [comment] 2023-09-11 09:45
@rougier I think I will need your help for the publication process.

**Comment by ViniciusLima94** [comment] 2023-10-11 08:42
Dear editors,

Since it has been some time since the approval of our manuscript, we would like to kindly ask if there is a prevision of the publication release?

Also, let us know if there is something in which we can be helpful.

Cordially,
The authors

**Comment by rougier** [comment] 2023-10-13 11:14
My fault. Can you give me the url to your latex sources (will be easier for me)?

**Comment by ViniciusLima94** [comment] 2023-10-13 11:40
Dear @rougier 

Is this link enough? https://www.overleaf.com/2655993686zbxxybtskpct

Cordially

**Comment by rougier** [comment] 2023-11-16 15:03
Sorry for loooonnng delay. Zeonodo API has just changed and I need to adapt the published script but for that I need their input on how to do it. Can you ping me here again on Monday to make sure to not have further delay in publishing? In the meantime, you can try to fill as much data as possible in the metadata.tex.

**Comment by ViniciusLima94** [comment] 2023-11-20 11:32
Dear @rougier ,

I'm pinging you as you requested.

I also just pushed a version of the "metadata.tex", with more information inserted. Let me know if there is anything else I can help with.

Best,
Vinicius.

**Comment by rougier** [comment] 2023-11-22 15:30
Thanks. Zenodo problem is fixed. Could you fill in the matadata.yaml instead (since the .tex i generated from .yaml). I'll then download you overleaf and work from here.

**Comment by ViniciusLima94** [comment] 2023-11-22 15:48
Dear @rougier ,

Thank you! I just pushed the metadata.yaml file already edited.

Best,
Vinicius.

**Comment by rougier** [comment] 2023-12-04 11:01
Sory for new delay. Actually, the `metadata.yaml` file needs to be updated. @benoit-girard can you fill the metadata.yaml file with relevant information and send it to me here ?

**Comment by benoit-girard** [comment] 2023-12-04 14:50
@rougier I just sent it to you.

**Comment by rougier** [comment] 2023-12-04 16:35
Here is the sanbox version, @ViniciusLima94 can you check everything's ok (then I'll publish the finale version)
https://sandbox.zenodo.org/record/5947

**Comment by ViniciusLima94** [comment] 2023-12-04 16:40
Dear @rougier ,

Thank you.

Everything seems to be fine except for the link to the original publication codes, in the section "Availability of code implementations for the original model".

![image](https://github.com/ReScience/submissions/assets/17538901/3f703b46-01a0-413b-a6e2-fc2b9f5e90ae)

**Comment by rougier** [comment] 2023-12-04 17:19
Ah, weird. Was it the case on your version ? By the way, software heritage is a better option for savig  software but we can live with this url. I think there's a latex package to break url but I need to find its name.

**Comment by ViniciusLima94** [comment] 2023-12-04 18:15
In the overleaf version was fine.

I saw some solutions suggesting to use the hyperref package.

```
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\url{http://www.example.com/this/is/a/very/long/url/that/should/be/broken}

\end{document}
```

**Comment by rougier** [comment] 2023-12-04 19:52
Thank. Hyperref is already loaded in the rescience class. But it needed the `xurl` package. By they way, when you need only the url, you can use `\url{some address}` instead of `\href{some address}{some address}`

**Comment by rougier** [comment] 2023-12-04 19:53
If the rest of the paper is ok I'll publish it. Waiting for your go.

**Comment by ViniciusLima94** [comment] 2023-12-04 19:56
Great thanks @rougier ,

I didn't know about the \url, thanks 

The rest of the paper was fine, so for me it is good to go 😁

**Comment by rougier** [comment] 2023-12-04 20:31
Here it is: https://zenodo.org/record/10257800.
It'll appear soon the journal website.

**Comment by ViniciusLima94** [comment] 2023-12-05 12:45
Dear @rougier ,

I just noticed a problem in one of the authors affiliation.

It is my fault since the info was wrong in the "metadata.yaml" (Antonio C. Roque, is acually affiliation 3). I don' know if it is possible to correct it, I already pushed the "metadata.yaml" with the correction.

I'm really sorry about that.

Best,
Vinicius.

**Comment by rougier** [comment] 2023-12-05 17:23
Aarrrrrrrggggggg.... But yes, we can add a new version I think. So only correction is Antonio 1,4 to Antonio 3 ?

**Comment by ViniciusLima94** [comment] 2023-12-05 17:28
Hi @rougier ,

Exactly, I have updated his orcid also on the metadata.yaml.

Thank you very much, and sorry for the trouble.

Best.

**Comment by rougier** [comment] 2023-12-05 21:08
No wait, you mean orcid is wrong too? What is the right orcid number?

**Comment by ViniciusLima94** [comment] 2023-12-06 07:45
Yes, it is the one I put on the metadata.yaml,

orcid: 0000-0003-1260-4840

**Comment by rougier** [comment] 2023-12-06 09:30
Here is the new DOI: https://zenodo.org/records/10276194

**Closed as completed** 2023-12-06 09:30 UTC
Labels: DOM: Neuroscience, LANG: Python, TYPE: Replication, 01 - Request, DOM: Computer Science
