### ISSUE TITLE
Ten Years Reproducibility Challenge: Identifying essential genes by mutagenesis

### ISSUE THREAD

**Issue by kbroman** [ReScience/submissions#18] opened 2020-02-17 20:08 UTC
**Original article:** Lamichhane G, Zignol M, Blades NJ, Geiman DE, Dougherty A, Broman KW, Bishai WR (2003) A post-genomic method for predicting essential genes at subsaturation levels of mutagenesis: application to Mycobacterium tuberculosis. Proc Natl Acad Sci USA 100:7213-7218 [doi:10.1073/pnas.1231432100](https://doi.org/10.1073/pnas.1231432100)

**PDF URL:**  https://kbroman.org/Paper_ReScience2020/article/article.pdf
**Metadata URL:**  https://github.com/kbroman/Paper_ReScience2020/blob/master/article/metadata.yaml
**Code URL:**  https://github.com/kbroman/Paper_ReScience2020

**Scientific domain:**  Genetics
**Programming language:**  R
**Suggested editor:**  @karthik

**Comment by rougier** [comment] 2020-02-20 05:48
@kbroman Thanks, we'll soon assign an editor.
@ReScience/editors Can someone handle this submission (finding an editor or editing yourself) ? Note that for the Ten Years Reproducibility Challenge, only one reviewer is needed.

**Comment by karthik** [comment] 2020-02-21 03:01
I can handle this

**Comment by rougier** [comment] 2020-02-21 10:02
Thansk, I've just assigned you. you can use the `@ ReScience / reviewers` to call for reviewers if you want.

**Comment by rougier** [comment] 2020-02-28 15:39
@karthik Gentle reminder

**Comment by rougier** [comment] 2020-06-15 05:39
@kbroman  Sorry for being so late, our editorial procedure needs some automatic reminders @karthik We're very late on this submission. Can you assign a reviewer?

**Comment by karthik** [comment] 2020-06-15 05:50
Apologies @kbroman and @rougier. I've had a lot of declines in review requests across various journals for a while. Will definitely assign someone this coming week.

**Comment by karthik** [comment] 2020-06-16 01:10
@rougier emailed you a procedural question.

**Comment by karthik** [comment] 2020-07-02 20:49
:wave: Hi @pcarbo Would you be able/willing to review this submission for us? 🙏

**Comment by karthik** [comment] 2020-07-02 20:50
👋 Hello @kasperdanielhansen 
I also wanted to see if you might be able to review this submission for us? 🙏

**Comment by pcarbo** [comment] 2020-07-03 17:44
@karthik Are there instructions for the reviewers? If so, could you please point me to them?

**Comment by karthik** [comment] 2020-07-03 19:18
@pcarbo Thank you! Review instructions are here: https://rescience.github.io/edit/
Feel free to ask any questions here. Once again thank you.

**Comment by karthik** [comment] 2020-07-06 17:39
@pcarbo Once you've taken a look at the instructions please let me know once your review is underway.

**Comment by pcarbo** [comment] 2020-07-06 18:33
@karthik I just want to be clear what you are looking for. Are these the instructions from [here](https://rescience.github.io/edit) that are relevant to me?

> During the review, reviewers are free to interact with the authors to ask for clarification or change in any file that is part of the submission. The main criterion for acceptance is either: Replication of the original research with a clear statement by the authors explaining why they think they have replicated the paper (same figures, same graphics, same behavior, etc). Non-replication of the original research with a clear statement by the authors explaining why they believe that it cannot be replicated. Source code without any accompanying article is also a criterion for rejection since we’re not human compilers (well not all of us at least).
```

**Comment by karthik** [comment] 2020-07-06 18:38
@pcarbo Some might not be relevant to this challenge as Karl is replicating his own work a decade later. So you can ignore these. Your goal is to run the code and see if Karl's reproducibility report (the PDF) matches your experience. You are still welcome to contact (tag) the author with questions and clarifications.

Here is an example review: https://github.com/ReScience/submissions/issues/32#issuecomment-633739558

**Comment by pcarbo** [comment] 2020-07-15 01:12
@karthik @kbroman Leah Wang (@lwa19) and I enjoyed going through Karl’s [report][article] and [code][repo], and reading about his experiences trying to reproduce the results of a paper written (well over!) 10 years ago. As you may know, we (together with @jdblischak and @stephens999) have been developing the [workflowr R package][workflowr-pkg] (see also [the workflowr paper][workflowr-paper]) to help researchers develop more reproducible code, and Karl’s remarks at the end of his article ("Lessons") suggest that workflowr could have prevented or alleviated several of the difficulties; in particular, workflowr facilitates, or automates, setting the random seed, maintaining a project history (with git), generating reports (with R Markdown), and better project organization. Our comments here focus on our experiences using Karl’s code to reproduce his results.

First, and foremost, we were able to successfully reproduce [Karl’s results][reproduction]. The instructions are sufficiently detailed and easy to follow; in particular, it was helpful to have a single R Markdown file giving a start-to-finish set of steps for generating the results. We ran the code on the high-performance computing cluster run by the University of Chicago’s Research Computing Center; see [Leah's fork of Karl’s repository][repo-fork] for details, and in particular [Leah's reproduction of the report][reproduction-copy]. The only issue was that there was some knitr-specific syntax in the code chunks, e.g., `<<run_sept02_mcmc>>`, that gave RStudio some trouble depending on how the code was run. For cross-compatibility perhaps this syntax is best avoided. The remaining comments touch on are some areas where we found the code difficult to follow, and include some small suggestions for improvement (say, with a 50-year Reproducibility Challenge in mind):

+ Changing the working directory multiple times during the analysis made it hard to keep track of the file paths, which files are being loaded, and where files are being saved to, certainly when the code is being run interactively. It would be better to have a single working directory throughout and define all the file paths relative to that directory.

+ The "table4" code chunk was confusing because of the way that the code was modified on the fly; it seems that this could have been handled more simply by defining a variable, e.g., `cutoff <- 75`, and using that instead of hardcoded values.

+ Instead of clearing the workspace with `rm(list = ls())`, it may have been better to split the analysis into multiple R Markdown files that are listed in a "master" R Markdown file.

+ Since the MCMC step took a some time to run, it would have been helpful to give a warning, and some sense of expected runtime.

+ There is some bookkeeping at the beginning—moving and renaming files—and perhaps it would have been better to commit these changes to the git repository, and not include in the script.

+ The code and results were saved to a single folder, `Paper_ReScience2020/reproduction/R`. This is what we see:

    ```
    circlefig.R
    figs4paper.R
    nov02_analysis.R
    nov02_data.RData
    nov02_prepareData.R
    nov02_results.RData
    prob_essential.ps
    sept02_analysis.R
    sept02_data.RData
    sept02_prepareData.R
    sept02_results.RData
    ```

  It would have been helpful to create folders such as "code", "data" and "output" to make clear which are the inputs and which are the outputs.

+ When you said, "Here is the reconstruction of Table 3", what you really meant, we believe, is Supplement Table 6 (which is the same as Table 3, but with the longer list of genes). There were a couple spots where the explanations weren't clear, at least without being familiar with later steps in analysis; please also see [the comments included in the R Markdown][reproduction-copy].

Please assign most of the credit for this review to Leah Wang (@lwa19). She worked through Karl’s [report][reproduction], reproduced his results and provided most of the feedback on the code.

[article]: https://kbroman.org/Paper_ReScience2020/article/article.pdf
[repo]: https://github.com/kbroman/Paper_ReScience2020
[repo-fork]: https://github.com/lwa19/Paper_ReScience2020
[reproduction]: https://kbroman.org/Paper_ReScience2020/reproduction/reproduction.html
[reproduction-copy]: https://lwa19.github.io/Paper_ReScience2020/reproduction/reproduction.html
[workflowr-pkg]: https://cran.r-project.org/package=workflowr
[workflowr-paper]: https://doi.org/10.12688/f1000research.20843.1

**Comment by kbroman** [comment] 2020-07-15 22:02
@pcarbo and @lwa19, thanks so much for your detailed comments, and for your efforts to reproduce my reproduction! I really appreciate the feedback. 

I can see that my reproduction was complicated and cringe-inducing in places. I had in mind leaving the original scripts and data files in their place exactly as they were and using a single R Markdown document to modify and re-run things; that was probably not the best choice.

**Comment by karthik** [comment] 2020-07-15 22:21
Thanks so much @lwa19 and @pcarbo! Very grateful for your review. 

@kbroman I opened a PR with some small fixes to your README.

**Comment by karthik** [comment] 2020-07-15 22:33
Noting the original request here (for my own reference) https://github.com/ReScience/ten-years/issues/1#issuecomment-546353681

**Comment by karthik** [comment] 2020-07-16 19:43
@pcarbo and @lwa19 Can you please share your ORCID for the paper metadata? Once I have it I'll send another pull request to Karl's repository.

**Comment by karthik** [comment] 2020-07-16 19:46
ok I found Peter's. 0000-0003-1144-6780
Leah: Can you confirm yours? Is it this record?  https://orcid.org/0000-0003-3085-2581

**Comment by pcarbo** [comment] 2020-07-16 19:57
Yes, that is my orcid.

**Comment by pcarbo** [comment] 2020-07-16 19:57
I've asked Leah to create one.

**Comment by pcarbo** [comment] 2020-07-16 20:04
@karthik This is Leah's: https://orcid.org/0000-0001-5905-8061.

**Comment by karthik** [comment] 2020-07-24 20:26
@kbroman Im just waiting to correctly deposit the metadata into Zenodo before I close this out. Stay tuned.

**Comment by khinsen** [comment] 2020-08-19 07:22
@karthik Since this paper is now published, can we close this issue?

**Comment by karthik** [comment] 2020-08-19 07:23
Of course.

**Closed as completed** 2020-08-19 07:23 UTC
Labels: DOM: Biology, LANG: R, 01 - Request, 02 - Review, 03 - Accepted, 04 - Published, Ten Years Challenge, TYPE: Reproduction
