### ISSUE TITLE
[Re] The Evolution of Virulence in Pathogens with Vertical and Horizontal Transmission

### ISSUE THREAD

**Issue by kiristern** [ReScience/submissions#56] opened 2021-05-09 16:02 UTC
**Original article:**
M. Lipsitch, S. Siller, and M. A. Nowak. “THE EVOLUTION OF VIRULENCE IN PATHOGENS WITH VERTICAL ANDHORIZONTAL TRANSMISSION.” In:Evolution50.5 (1996), pp. 1729–1741. eprint:https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1558-5646.1996.tb03560.x.

**PDF URL:**
https://github.com/BIO6032/2021_replication_LipstichEtAl_1996/blob/master/Manuscript/2021_replication_LipstichEtAl_1996.pdf
**Metadata URL:**
https://github.com/BIO6032/2021_replication_LipstichEtAl_1996/blob/master/Manuscript/metadata.yaml

**Code URL:**
https://github.com/BIO6032/2021_replication_LipstichEtAl_1996

**Scientific domain:**
Epidemiology

**Programming language:**
Julia

**Suggested editor:**
@karthik 

**Co-authors**
@faresdhane @sandrinesoeharjono @aammd @tpoisot

**Comment by rougier** [comment] 2021-05-17 08:14
Thanks for your submission and sorry for  the delay. We'll assign an editor soon.

@karthik Woudl be available to edit this submission?
@kiristern Could you propose some reviewers (e.g. from https://rescience.github.io/board/ but it's not mandatory to pick names from the board)

**Comment by kiristern** [comment] 2021-05-17 13:40
@ChrisRackauckas are you available and willing to review our submission?

**Comment by ChrisRackauckas** [comment] 2021-05-17 14:00
I will not have adequate time to do so, sorry. But I would possibly recruit Simon Frost or Affan Shoukat

**Comment by kiristern** [comment] 2021-05-17 14:48
@ChrisRackauckas no worries, thank you for the suggestions!
@sdwfrost @affans would either of you have the time to review our submission?

**Comment by affans** [comment] 2021-05-18 15:25
@kiristern I'd be happy to review. Please let me know what the procedure is (are you submitting to a journal?). I am not familiar with ReScience.

**Comment by sdwfrost** [comment] 2021-05-18 16:11
@kiristern I'm also happy to take a look if you need me.

**Comment by kiristern** [comment] 2021-05-18 16:23
@affans @sdwfrost Thank you so much for your involvement! Reviewer guidelines for ReScience journal can be found here: http://rescience.github.io/edit/

**Comment by rougier** [comment] 2021-05-19 10:14
Ah ah, thanks @kiristern. It was supposed to be the role of the editor (that is yet to named) but if @sdwfrost and @affans are ok to review, we can start.

**Comment by rougier** [comment] 2021-05-19 10:15
@karthik Can you handle this submission (reviewers have been found already)?

**Comment by rougier** [comment] 2021-05-28 13:02
ping @karthik

**Comment by stephanmg** [comment] 2021-06-07 07:35
Would also happily review this @rougier

**Comment by affans** [comment] 2021-06-07 16:01
Hi Sorry, I've been swamped with work (and also moving across borders). I will get to this soon. 

Thanks,

**Comment by rougier** [comment] 2021-06-14 07:12
Ok. Thanks @stephanmg @affans. If you can start review that would be great.

**Comment by rougier** [comment] 2021-06-21 16:53
@stephanmg @affans Gentle reminder.

**Comment by stephanmg** [comment] 2021-06-22 06:01
@rougier I didn't forget I will review by end of month. My preliminary review:

Figures: All okay - except not grayscale anymore (compared to original publication)

Review criteria:
Reproducibility of the replication on Ubuntus 20.04/20.10: Followed instructions in README.md an worked out of the box.
Clarity and completeness of the accompanying article: OK.
Clarity of the code: A lot of whitespace and blank lines, please remove blank lines.
Clarity and completeness of the accompanying article: OK.

**Revisions:**
- Remove blank lines and superfluous whitespace in all `.jl` files.
- Switch documentation from plain comments in `.jl` files to Julia Documenter https://juliadocs.github.io/Documenter.jl/stable/

**Comment by rougier** [comment] 2021-06-29 08:30
@stephanmg Thanks for preliminary review. @kiristern Can you address these technical points?

**Comment by kiristern** [comment] 2021-06-29 13:44
@rougier Yes, we will go over this shortly. 
@stephanmg Thank you for your feedback!

**Comment by affans** [comment] 2021-06-29 17:50
@rougier 
I have finished reviewing the paper and I have some comments. 

**Comments:**
First, the paper is very well written and easy to follow. I would suggest adding some interpretation to some of the equations for non-experts in the subject matter. For example, a few sentences explaining the terms in the calculation of reproduction numbers and the justification/assumptions in  equations 7 - 11. 

It might be beneficial to see the dynamics of the model early in the solution trajectory before equilibrium sets in. For instance, in figure 1A/B, would it be possible to show an inset plot for the first n time points?

**Review Criteria:** 
The actual replication of the research. I am unfamiliar with the original manuscript by Lipsitch (but did quickly go over it). The figures seem to replicate the original results, although see my comment above about improving some of the figures. The interpretation of the results are equivalent in both papers (mainly that of the selection pressures of vertical transmission). 

Clarity of the code and the instructions for running it: OK. The code could use a little more documentation. I would also recommend the authors review the [Julia's page on performance](https://docs.julialang.org/en/v1/manual/performance-tips/) to optimize the code a bit. For example, declaring `const` globals, and making use of functions. 

Reproducibility of the replication:  **Not acceptable**. I was able to reproduce on Julia 1.6.  See error below: 

```
julia> include("Model_scripts/00run_project.jl")
ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: UndefVarError: @progress not defined
Stacktrace:
  [1] top-level scope
    @ :0
  [2] #macroexpand#50
    @ ./expr.jl:112 [inlined]
  [3] macroexpand
    @ ./expr.jl:111 [inlined]
  [4] docm(source::LineNumberNode, mod::Module, meta::Any, ex::Any, define::Bool) (repeats 2 times)
    @ Base.Docs ./docs/Docs.jl:537
  [5] (::DocStringExtensions.var"#29#30"{typeof(DocStringExtensions.template_hook)})(::LineNumberNode, ::Vararg{Any, N} where N)
    @ DocStringExtensions ~/.julia/packages/DocStringExtensions/w58MB/src/templates.jl:11
  [6] var"@doc"(__source__::LineNumberNode, __module__::Module, x::Vararg{Any, N} where N)
    @ Core ./boot.jl:508
  [7] include(fname::String)
    @ Base.MainInclude ./client.jl:444
  [8] top-level scope
    @ ~/rescience-review/Model_scripts/fig1acegi.jl:5
  [9] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [10] top-level scope
    @ ~/rescience-review/Model_scripts/00run_project.jl:1
 [11] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [12] top-level scope
    @ REPL[2]:1
in expression starting at /home/affan/rescience-review/Model_scripts/Functions.jl:21
in expression starting at /home/affan/rescience-review/Model_scripts/Functions.jl:19
in expression starting at /home/affan/rescience-review/Model_scripts/Functions.jl:19
in expression starting at /home/affan/rescience-review/Model_scripts/fig1acegi.jl:5
in expression starting at /home/affan/rescience-review/Model_scripts/00run_project.jl:1
```
Package status: 
```
(rescience-review) pkg> st
      Status `~/rescience-review/Project.toml`
  [0c46a032] DifferentialEquations v6.16.0
  [31c24e10] Distributions v0.24.18
  [e30172f5] Documenter v0.27.3
  [91a5bcdd] Plots v1.13.1
  [9a3f8284] Random
```
Version information: 
```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

Please tag me once this error has been fixed (or maybe provide me with instructions on how to fix the error). I will rerun the code again.

**Comment by stephanmg** [comment] 2021-06-29 18:06
@affans so 1.6.0 fails for you? Did you try 1.6.1?

**Comment by affans** [comment] 2021-06-29 18:08
No, I suppose I will try it. The README did say `This project is a Julia 1.6.0 replication of Lipsitch et al` so I thought 1.6.0 was good. I will have to download and setup 1.6.1 for myself.

**Comment by kiristern** [comment] 2021-06-29 18:09
@affans Sorry for the error, @faresdhane @sandrinesoeharjono @aammd @tpoisot and I are in the midst of incorporating @stephanmg suggestions and switching file documentation to Julia Documenter. I will see if reversing the `pkg add Documenter` commit fixes the problem, as we won't be able to get around to formatting until early next week.

**Comment by affans** [comment] 2021-06-29 18:15
No problem. Just tag me, and I'll be happy to run again. Great job on the paper!

**Comment by kiristern** [comment] 2021-06-29 18:25
@affans okay, should run now. Please pull the latest commits and let us know if there are any issues. Thanks!

**Comment by tpoisot** [comment] 2021-06-29 18:37
@kiristern / @affans I'm quite sure this is because the `@progress` macro works in Juno, but not generally in a julia REPL - give me a few minutes to replace it by a `@showprogress` macro which is more general, sorry about that.

**Comment by kiristern** [comment] 2021-06-29 18:45
@tpoisot ooh i see. I completely glossed over the actual error and was only thinking of the things we changed since it last ran properly. Thanks for the catch

**Comment by affans** [comment] 2021-06-29 18:54
If that is the case, I'd suggest removing it all together (or maybe adding a dependency on `ProgressMeters.jl`). That way it will work out of vscode/repl/vim etc etc.

**Comment by tpoisot** [comment] 2021-06-29 18:54
I have opened a pull request, check that it runs, and this should fix the issue @affans was having - I added `ProgressMeter` (and ran the code through a formatter)

**Comment by rougier** [comment] 2021-07-05 07:04
@stephanmg Gentle reminder

**Comment by stephanmg** [comment] 2021-07-05 07:11
Is the code/PR merged?

**Comment by kiristern** [comment] 2021-07-05 11:45
Going over it this evening with the rest of the authors

**Comment by stephanmg** [comment] 2021-07-05 11:56
Let me know, when the changes have been added. I'm re-running the code then and give my final review.

**Comment by kiristern** [comment] 2021-07-05 22:17
@stephanmg `ProgressMeter` works now. Feel free to run the code. Awaiting your final review. Thank you so much

**Comment by affans** [comment] 2021-07-06 04:06
*Updated Review*

Please see first review comments here: https://github.com/ReScience/submissions/issues/56#issuecomment-870795734

For this updated review, I was able to do a `git pull` and was able to run the code successfully. I am still not able to verify the plots are being correctly generated (**although this is no fault of the authors** -- my computer is unable to generate them). 

See output of the script: 

```
julia> include("Model_scripts/00run_project.jl")
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:01:30
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:01:04
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:00:38
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:00:55
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
read: Connection reset by peer
send: Broken pipe
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:01:05
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
Progress: 100%|████████████████████████████████████████████████████████████████████████████| Time: 0:01:25
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-affan'
```

The errors are likely because I am using WSL2 within Windows. I do have an `X` server running which correctly pushes graphics to my computer, but I am not sure whats really happening here.

**Comment by stephanmg** [comment] 2021-07-06 07:24
I confirm that the `ProgressMeter` works for me now and I have no further comments, figures are reproduced for me as well on Ubuntu @affans. 

@kiristern did you add amend the code based on my recommendations for formatting and documentation? The code looks better now and I would say I can okay this.

**Comment by rougier** [comment] 2021-07-12 08:26
@kiristern Can you answer questions by @stephanmg and @affans ?

**Comment by kiristern** [comment] 2021-07-12 20:33
Sorry for the delay.

@stephanmg yes we formatted scripts according to your recommendation, minus fully switching to Documenter.jl. Other ReScience replications in Julia used comments and we believe that the comments help with the clarity of our code, without needing to completely reformat everything. 

@affans we will be going over the text to include clarification of equations, as well as your other suggestions, hopefully sometime this week. Will let you know once it's done!

Thanks.

**Comment by stephanmg** [comment] 2021-07-13 05:47
Then fine from my part.

**Comment by kiristern** [comment] 2021-07-21 14:08
@affans thank you for your patience. We've included all your suggestions and have updated our manuscript to reflect 1) description of equations; 2) plots of population dynamics before equilibrium (in supplemental figures); 3) optimized code.

**Comment by rougier** [comment] 2021-07-26 09:03
@stephanmg Many thanks for your review and answer.
@affans If you're satisfied with modifications and corrections, we can can proceed with acceptance and publication.

**Comment by kiristern** [comment] 2021-08-11 14:18
hi @affans any feedback on our last update? Thanks!

**Comment by kiristern** [comment] 2021-08-17 16:53
@rougier still waiting for @affans final review, but in the meantime, just wondering about the editor role... @karthik hasn't responded so is it my job to find someone else? Thanks

**Comment by karthik** [comment] 2021-08-18 05:07
I'm out on paternity leave for a few months. So please find someone else.

**Comment by affans** [comment] 2021-08-18 13:36
Hello, sorry for the late response. I am satisfied with the latest update.

**Comment by kiristern** [comment] 2021-08-18 14:28
@affans Great, thank you so much!
@rougier what would be the next steps to proceed with the acceptance and publication process?  
@sdwfrost would you be still willing to go over our submission as the editor?

**Comment by kiristern** [comment] 2021-08-27 13:52
@rougier if @sdwfrost isn't able to act as editor, would you be able to recommend someone or would I need to reach out to someone from the https://rescience.github.io/board/ members?

**Comment by tpoisot** [comment] 2021-08-30 14:09
@rougier just a ping (I know the fall term is hard on everyone!) - do you want us to approach another editor, or can you take care of the next steps?

**Comment by rougier** [comment] 2021-09-06 08:35
Hi all, sorry for the late answer. I'll take the role of editor and proceed with the next steps.
I think @affans and @stephanmg are both satisified such that we can accept the submission. Congratulation @kiristern!

For actual publication, can you give me the link to the latex sources (may be easier for me to directly edit it).

**Comment by kiristern** [comment] 2021-09-07 15:37
Amazing, thank you so much @rougier ! I exported our Overleaf and uploaded it to our github under LaTeX https://github.com/BIO6032/2021_replication_LipstichEtAl_1996/tree/master/LaTeX our text is found in the content.tex file

**Comment by tpoisot** [comment] 2021-09-22 20:19
@rougier is there something we can do to help with the editing?

**Comment by rougier** [comment] 2021-10-04 08:13
Not at all, I did not see @kiristern gave me the link. I'll edit it today.

**Comment by rougier** [comment] 2021-10-04 08:31
@tpoisot @kiristern I would need you to update your article template from https://github.com/ReScience/template and to register your code at https://www.softwareheritage.org/save-and-reference-research-software/ such as to get a SWID.

**Comment by tpoisot** [comment] 2021-10-04 11:51
> @tpoisot @kiristern I would need you to update your article template from https://github.com/ReScience/template and to register your code at https://www.softwareheritage.org/save-and-reference-research-software/ such as to get a SWID.

@kiristern can you take care of this?

**Comment by kiristern** [comment] 2021-10-04 12:40
@faresdhane @sandrinesoeharjono could either of you look into this? Otherwise, I will only be able to get to this at the end of the week.

**Comment by sandrinesoeharjono** [comment] 2021-10-17 04:32
Hi @rougier! 

So it turns out we hadn't updated our LaTeX scripts (and so we did not have the most recent bugfixes ReScience had made to the template repository). I've since remedied the situation (see [p-r](https://github.com/BIO6032/2021_replication_LipstichEtAl_1996/pull/32)) and the `make` command can now properly be executed. I want to note that I do observe a bizarre `pdflatex: Command for 'pdflatex' gave return code 1` log, although this is only _after_ the PDF is successfully created.

I've also followed the Software Heritage steps in order to register the code; it's submission has been accepted.

Everything has been merged to [master](https://github.com/BIO6032/2021_replication_LipstichEtAl_1996) and should be available to you. Thank you!

**Comment by rougier** [comment] 2021-10-18 08:55
I got some undefined sequences when trying to compile your PDF (`\mysubscript` and `\sidesubfloat`). Are you using specific packages for those?

**Comment by kiristern** [comment] 2021-10-18 11:56
Looking at our first copy, i found `\newcommand{\mysubscript}[1]{\raisebox{-0.34ex}{\scriptsize#1}}` added in our old `header.tex`... I vaguely remember having subscript issues when we were first writing up our article so this must have been the work around. I just went back into the `context.tex` and replaced where the `\mysubscript` function was with `$Y_{1.0}$` and it seems to compile fine (ie.`\mysubscript` can be deleted).
As for the `\sidesubfloat`, it appears to be related to figure labelling (a,b,c...). In our old `rescience.cls`, I found an added `%Subfigures` section with 
`\usepackage{floatrow}
\usepackage[label font=bf,labelformat=parens]{subfig}
\usepackage{caption}
\floatsetup[figure]{style=plain,subcapbesideposition=top}`
I think this too can be deleted as with the new template, the figure subplot labels appear in the lower left of the image (instead of top left), which isn't a big deal if that's how it should be formatted.

**Comment by sandrinesoeharjono** [comment] 2021-10-19 03:48
Hi @rougier,

My apologies. We've fixed both issues and pushed the latest modifications onto `master`. Please note that we've added the line `\usepackage{subfig}` in `article.tex`; I hope it doesn't infringe upon your ReScience template.

Thanks in advance!

**Comment by rougier** [comment] 2021-10-19 06:21
Now I got `! LaTeX Error: Option clash for package graphicx.` Do you also get it ? If so, can you try to clean your LaTeX directory and recompile from clean directory. Other option is for you to fill metadata (you'll need some information).

**Comment by rougier** [comment] 2021-10-19 17:45
Seems, to work now. Will try to publish tomorrow. Sorry for all the delays.

**Comment by rougier** [comment] 2021-10-19 18:25
Do you have the SWID from software heritage ?

**Comment by sandrinesoeharjono** [comment] 2021-10-19 22:24
@rougier I have not gotten any news from them since the submission. If I don't hear back from them within a day or two, I can contact them again (or try another submission).
<img width="1438" alt="Screen Shot 2021-10-16 at 1 44 34 AM" src="https://user-images.githubusercontent.com/46568441/137998945-6bb5d0b5-b345-4966-90f1-1e82426b2f03.png">

**Comment by rougier** [comment] 2021-10-20 05:17
Oh, ok. Tell me as soon as you get the ID.

**Comment by rougier** [comment] 2021-10-20 05:18
By the way, did you update the template? I cannot see the `swid` entry in the metadata.yaml

**Comment by kiristern** [comment] 2021-11-07 20:41
@sandrinesoeharjono did you hear back about the SWID ID ?

**Comment by sandrinesoeharjono** [comment] 2021-11-09 01:08
@rougier Sorry about the delay; I never heard back from them.
I can now however see that the repository did get added to the [archive](https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/BIO6032/2021_replication_LipstichEtAl_1996) and the SWHID associated with it is also available:
`swh:1:dir:c0bcbeb993bac32949bc8f0b2a218673899790e7;origin=https://github.com/BIO6032/2021_replication_LipstichEtAl_1996;visit=swh:1:snp:324470d93d3bc1702e773ac9fc8cca3b125727f7;anchor=swh:1:rev:d0d7b87f0a79ddc9e111985b1222eadf7924204d`

Would that be sufficient?

**Comment by rougier** [comment] 2021-11-22 08:09
@sandrinesoeharjono Yes, sorry for the delay. Let's try to publish it today. I'll make first a sandbox version that you can check and I'll publish it. Stay tuned.

**Comment by rougier** [comment] 2021-11-22 08:31
@sandrinesoeharjono  Can you check if https://sandbox.zenodo.org/record/965679 looks correct? This is a sandbox version, not the actual publication

**Comment by kiristern** [comment] 2021-11-22 14:58
@rougier looks good to me. I noticed the supplemental figures, which were a [suggestion](https://github.com/ReScience/submissions/issues/56#issuecomment-870795734) in the review process: 
> It might be beneficial to see the dynamics of the model early in the solution trajectory before equilibrium sets in. For instance, in figure 1A/B, would it be possible to show an inset plot for the first n time points?

have been omitted. No problem, just confirming this was a deliberate edit in the sandbox version.

**Comment by rougier** [comment] 2021-11-22 17:28
Oh, you mean there's a missing figure? I get latest changes from your repository and build the PDF again. Can you check if you pushed all your change on GitHub?

**Comment by kiristern** [comment] 2021-11-22 17:53
ah, i noticed that while all the supplementary figures were properly uploaded, we were missing the ```supplementary.tex``` file, which i've now included as well as an update to the ```article.tex``` file to call the suppl. figures at the end of the document. Sorry about that

**Comment by rougier** [comment] 2021-11-22 18:33
No problem, I'll rebuild the pdf and use it for final publication (unless you want to double check the new PDF). Can you confirme the Zenodo entry looks right to you (authors, links, keywords, etc)?

**Comment by kiristern** [comment] 2021-11-22 18:46
Authors, links, keywords all look good to me. However, I just noticed that the abstract wasn't compiled from the ```metadata.yaml``` file, ideas why?
Do @sandrinesoeharjono @faresdhane @tpoisot @aammd want to take a final look before it gets published?

**Comment by rougier** [comment] 2021-11-23 06:01
You mean inside the PDF or on Zenodo?

**Comment by kiristern** [comment] 2021-11-23 06:05
I was originally referring to not seeing the abstract in the PDF, but i can't seem to find it on Zenodo either

**Comment by rougier** [comment] 2021-11-23 07:09
Oh, do you see the abstract in your PDF when you build it locally?

**Comment by kiristern** [comment] 2021-11-23 14:13
hmm, from the previous version (before template update) the abstract appears, but i just downloaded the LaTeX folder from our github and ran it and it doesn't appear. Was there a change in the rescience template?

**Comment by rougier** [comment] 2021-11-23 21:19
I checked and it is actually commented. I'll put it back before publishing the final version.

**Comment by rougier** [comment] 2021-11-24 05:54
Article is online at at https://zenodo.org/record/5722853! Congratulations!!!

**Closed as completed** 2021-11-24 05:57 UTC
Labels: DOM: Biology, LANG: Julia, 01 - Request, 02 - Review
