### ISSUE TITLE
[Re] Reproduction of the normal and pathological dynamics in the basal ganglia-thalamo-cortical network

### ISSUE THREAD

**Issue by aleblois** [ReScience/submissions#28] opened 2020-04-17 09:55 UTC
**Original article**:  Leblois A, Boraud T, Meissner W, Bergmann H, Hansel D. Competition
between feedback loops underlies normal and pathological dynamics in the
basal ganglia. J Neurosci 26: 3567–3583, 2006.

**PDF URL**: https://github.com/aleblois/BGdynamics2006/blob/master/ReScience_C__BGdynamics2006.pdf
**Metadata URL**: https://github.com/aleblois/BGdynamics2006/blob/master/metadata.tex
**Code URL**: https://github.com/aleblois/BGdynamics2006
**yaml file**: https://github.com/aleblois/BGdynamics2006/blob/master/metadata.yaml

**Scientific domain: Neuroscience**  
**Programming language: C and Matlab**  
**Suggested editor**: Etienne Roesch, Tiziano Zito, Benoît Girard, Nicolas Rougier

**Comment by rougier** [comment] 2020-04-27 05:30
@benoit-girard Can you take care of this submission (either assign an editor or you can edit it youself). Only one reviewer needed since this is for the Ten Years Reproducibility Challenge.

**Comment by rougier** [comment] 2020-05-25 07:48
@benoit-girard ping !

**Comment by benoit-girard** [comment] 2020-05-26 12:19
I'm in!

**Comment by benoit-girard** [comment] 2020-05-26 12:19
I think I can review it myself.

**Comment by rougier** [comment] 2020-05-27 11:56
Perfect !

**Comment by rougier** [comment] 2020-06-15 05:43
Gentle reminder

**Comment by aleblois** [comment] 2020-06-15 07:01
Salut,On discute 5 min avant le début du cours?Arthur
    Le lundi 15 juin 2020 à 07:43:17 UTC+2, Nicolas P. Rougier <notifications@github.com> a écrit :  
 
 


Gentle reminder

**Comment by benoit-girard** [comment] 2020-06-18 14:17
I'm on it!

**Comment by benoit-girard** [comment] 2020-06-22 14:23
Overall, the paper is an interesting contribution to the 10-year reproducibility challenge. I suggest the correction of a number of minor points listed below:

Page 3, you mention that you had to correct a few mistakes in the matlab code to reproduce the analyses and the figures. Could you be more specific, as the paper is precisely about reproduction: what sort of mistakes are you talking about? Is it that the latest version of matlab required adjustments of your old code because of compatibility problems? Or that you found only on old version of the code that wouldn't have worked even in 2006, and that you had to re-make corrections you already did back in that time?

Is the figure 2 in the current manuscript a new figure generated in 2020, or a copy of the original figure? The compression artifacts tend to suggest it is the latter hypothesis, but it is not absolutely clear.

Page 2, you write "The description of the network studied in the 2006 paper (Figs 1&2 and Methods)", it is not clear if you are talking about the figures and methods of the 2006 paper, or of the current paper. As Fig. 2 of the curent paper does not really describe the model, and as there is no method section in the current paper, I assume you are talking about the 2006 one, but you should then state that explicitly.

Page 5, you write that you were able to produce "a set of figures identical or similar to the figures of the original paper"; are you referring to figures 3, 4 and 5? If yes, could you state it explicitly?

The following sentence in the introduction probably require reformulation: "The model for understanding how BG dysfunction leads to motor symptoms in (PD) and Huntingtonʼs disease was proposed 1,2" did you mean something like "The classical model for understanding how BG dysfunction leads to motor symptoms in (PD) and Huntingtonʼs disease has been proposed by 1,2"?

Formatting problems:
* page 2, the reference to Leblois et al. 2006 was not correctly compiled in "we designed a theoretical model of the BG-thalamo-cortical loop with a simplified connectivity pattern that did not require a segregation between the direct and indirect pathwaysLeblois:2006"
* Two sentences lost in the middle of the text seem to be incorrectly formatted subsection titles: "Description of the network model" (page 2) and "Retrieval of the software" (page 3).
* page 3: you have two dots at the end of  "the phase diagram(Fig. 2).."
* page 5: a number of references to figures were not compiled correctly, you end up with "??" rather than figure numbers on 7 occasions.
* page 5: you wrote "weekly", did you mean "weakly"?
* page 5, in the sentence "Rather, reproduction of the results consist in finding reproducing the behaviour of the network": "consist"->"consists", "finding reproducing" choose one or the other.
* page 5: "neural populations pf the network are activated" -> of the network
* page 7: "It provides a global understanding of the network dynamics the guide the numerical exploration" -> "that guides the numerical exploration" ?

**Comment by aleblois** [comment] 2020-06-25 14:12
Thank you for your comments. Here are my point-by-point answers, I hope they address the issues you raised. 

Page 3, I have corrected and added detail to explain what had to be changed in my previous matlab code. The text I added to the paper is the following: " First, a few functions had changed names or syntax and I had to correct the command line where I called the function to make my scripts compatible with the current version of Matlab I use. Secondly, the convention on the parameters and their values given in the text were not consistent between my Matlab code and the published paper. Indeed, a late change in a convention concerning one parameter (the cross-circuit weight gamma) was not defined in the same way in the published article and in most of the work I did before. We had changed this convention very late in the writing of the paper, and I had taken no note on this parameter change. In the published paper, the ratio between the STN-GPi connection gain within a loop and across loops was gamma, while in the previous paper it was gamma/(1-gamma). Once this parameter change was taken into account, all results could be retrieved. Archiving all conventions used for all parameters of the model is crucial for future use. "

Figure 2 was rebuild, as all other figures, and is not a copy from the original (the axes limits are actually slightly different). The compression artifact is simply due to the jpg export of the matlab original figure. 

In the description of the network model, I now explicitely refer to Fig1&2 and methods of the original 2006 paper. 

Page 5, I now refer explicitely to figures 3-5. 

The introduction sentence is now corrected. 

All formatting problems have been corrected. Thanks again for the careful editing, and my apologies for the many misprints and formatting errors.

**Comment by aleblois** [comment] 2020-06-25 14:22
Revised version:

PDF URL: https://github.com/aleblois/BGdynamics2006/blob/master/ReScience_Leblois2006_revisedversion.pdf
Metadata URL: https://github.com/aleblois/BGdynamics2006/blob/master/metadata.tex
Code URL: https://github.com/aleblois/BGdynamics2006

**Comment by benoit-girard** [comment] 2020-06-30 15:06
I am fully satisfied with the revised version of the paper, I recommend publication.

**Comment by benoit-girard** [comment] 2020-06-30 15:07
@rougier will you take care of the publication process? If not, is it still the same old long process, or has it changed somehow?

**Comment by rougier** [comment] 2020-06-30 20:33
There's a new publication process that is less painful but not yet fully automatic. Good news is that you can first test if on the Zenodo sandbox server and if everything works ok, you can do the actual publication. Else, I can do it, just tell me.

**Comment by rougier** [comment] 2020-06-30 20:34
Forgot the link: https://github.com/ReScience/articles

**Comment by rougier** [comment] 2020-09-08 14:22
Sorry for the delay. There's a new publication process available at  https://github.com/ReScience/articles which is supposed to be smoother. Do not forget to use the sandbox to check everything is fine first.

**Comment by benoit-girard** [comment] 2020-09-28 12:12
OK, I will start now trying to make the final publication steps with the new process.
Sorry for the delay.

**Comment by benoit-girard** [comment] 2020-09-28 12:30
@rougier first step, first questions... 
* there is a metadata.tex file in @aleblois 's repository, but I can't find the yaml one. Am I missing something? Should @aleblois provide it?
* the pdf currently does not indicate the name of the editor, of the reviewer, and the date of acceptance. Is it still OK for the first steps of the submission? Do I need to edit that myself (but I do not have the source, only the pdf...), or ask @aleblois to do it?

**Comment by benoit-girard** [comment] 2020-09-29 08:23
OK, reading the latest instructions for authors, I see that the author should provide the "mandatory" yaml file. 
@aleblois can you do that please?

**Comment by aleblois** [comment] 2020-10-14 10:30
Hi, sorry for the delay, I have added the link to the yaml file. Please let me know if you need anything else, or if it does not work. Best

**Comment by aleblois** [comment] 2020-10-14 10:33
Actually, the yaml file seems o have the wrong info (Rougier and Hinsen paper). I'm not sure how to edit/generate the yaml. Nicolas, any tip on this?

**Comment by aleblois** [comment] 2020-10-14 10:43
I edited manually the yaml file, which should be OK now. Best

**Comment by rougier** [comment] 2020-10-15 06:57
@aleblois Actually, this is the way to got with the yaml file (manual editing).
@benoit-girard tell me if you need help with the publication process.

**Comment by benoit-girard** [comment] 2021-02-16 13:22
OK, i am (finally) in the publication process. To which volume/issue should I associate the paper? Volume 6, Issue 1, Number 19?

**Comment by benoit-girard** [comment] 2021-02-16 13:39
@aleblois I have send a pull request on your repo, with an updated metadata.yaml file.
If I am not mistaken (@rougier ?), you will have to validate the request, and update your article.pdf with the new information (volume, issue, number, doi, editor, reviewer, dates of acceptance & publication).

**Comment by aleblois** [comment] 2021-02-16 13:59
Hey, I do not see any pull request on my repo.....

**Comment by benoit-girard** [comment] 2021-02-16 14:07
Ah... I probably did something wrong.

**Comment by benoit-girard** [comment] 2021-02-16 14:07
This : https://github.com/aleblois/BGdynamics2006/pull/1

**Comment by aleblois** [comment] 2021-02-16 14:20
I merged it, is it OK now? Sorry my Github experience is near zero....

**Comment by benoit-girard** [comment] 2021-02-16 16:30
That's perfect!

Now you have to regenerate you pdf, including the new metadata (that you will find in the metadata.yaml file) : 
volume 6, issue 1, number 19, doi 10.5281/zenodo.4543356, editor (me, orcid 0000-0002-8117-7064), reviewer (me also), dates of acceptance (June 30, 2020) & publication (February 16, 2021).

Tell me when it's done!

**Comment by aleblois** [comment] 2021-02-16 16:42
Done!

**Comment by benoit-girard** [comment] 2021-02-16 18:31
OK, but you haven't pulled it yet on github (or at least, I did not find it).

**Comment by aleblois** [comment] 2021-02-17 11:29
In aleblois/BGdynamics2006#1 (https://github.com/aleblois/BGdynamics2006/pull/1), the file ReScience_C__BGdynamics2006.pdf is the new PDF. Should I put it somewhere in https://github.com/ReScience/articles? Not sure where....

**Comment by rougier** [comment] 2021-02-17 11:35
@benoit-girard will upload the article to this repository actually.

**Comment by benoit-girard** [comment] 2021-02-17 19:36
@rougier I have the pdf, I am now at the publish step (step 11), I get an error I do not (yet?) understand:

```girard$ ./publish.py --sandbox --metadata metadata.yaml --pdf article.pdf
Uploading content to Zenodo... Traceback (most recent call last):
  File "./publish.py", line 204, in <module>
    upload_content(server, token, article_id, article_file)
  File "./publish.py", line 25, in upload_content
    raise IOError("%s: " % response.status_code + response.json()["message"])
OSError: 404: PID does not exist.```

**Comment by rougier** [comment] 2021-02-18 05:55
Important: you need to do tests first on the sandbox server

Did you do the process.sh step and get a pre DOI ?

**Comment by benoit-girard** [comment] 2021-02-18 19:36
Yep, I did all steps until step 11

**Comment by benoit-girard** [comment] 2021-02-18 19:37
By the way, the error above resulted from:

`./publish.py --sandbox --metadata metadata.yaml --pdf article.pdf`

It was on sandbox

**Comment by rougier** [comment] 2021-02-19 08:01
Did you update the metadata.yaml with the provided DOI (and ideally rebuild the PDF) ?

**Comment by benoit-girard** [comment] 2021-02-19 19:53
Possible problem: metadata was containing the Zenodo doi (not the sandbox one). To test that possibility, I replaced the doi in metadata.yaml with the one I obtained when I did the process.py on the sandbox, relaunched the publish.py on sandbox, and now it tells me "Metadata is newer than PDF, probably PDF needs to be rebuilt". OK great, that's normal, but in the end I don't know if this test on sandbox worked or not, and if not, grmbl.

**Comment by benoit-girard** [comment] 2021-02-19 20:00
Ok, with a little touch, it worked...

Well, I am not sure it fully worked: I obtained the following (some part of the output message documented at step 11 is not there, but there is no obvious error)
```
girard$ ./publish.py --sandbox --metadata metadata.yaml --pdf article.pdf
Uploading content to Zenodo... done!
Updating metadata to Zenodo... done!
Publishing on Zenodo... done!
Entry is online at https://sandbox.zenodo.org/record/730471
```

**Comment by rougier** [comment] 2021-02-22 08:06
Yes, I can see it! So now you can upload it on the actual Zenodo server (and you'll able to merge the new branch in this case). Note that one difficulty is that you need to produce a new PDF one you obtained the DOI such as to publish the paper with the right DOI.

In case of problems, you still have the option to modify the entry on the Zenodo website directly.

**Comment by benoit-girard** [comment] 2021-03-08 10:08
step 11 passed...

**Comment by rougier** [comment] 2021-03-08 10:33
Just got the notification on Zenodo (to be included in the ReScience collection)!

**Comment by benoit-girard** [comment] 2021-03-08 14:09
I managed to do step 13, but I am unsure about the PR : I could change the bib file and commit the change, so is a PR really necessary?

**Comment by rougier** [comment] 2021-03-08 14:26
The PR is mostly to tell me the bib item can be integrated such that I can rebuild the website (don't try to do it yourself or you might risk to break it).

**Comment by benoit-girard** [comment] 2021-03-08 15:35
The thing is that as the branch has been merged peacefully, I have nothing to include in a PR.

**Comment by rougier** [comment] 2021-03-08 15:42
Oh sorry, I was referring to the modification you need t do to the website (= add the new bib titem to the published.bib file)

**Comment by benoit-girard** [comment] 2021-03-09 14:02
I added the new bib item in the published.bib file : you can rebuild the website!

**Closed as completed** 2021-03-09 14:03 UTC
Labels: DOM: Biology, LANG: C/C++, 01 - Request, 02 - Review, 03 - Accepted, 04 - Published, Ten Years Challenge, TYPE: Reproduction

**Comment by rougier** [comment] 2021-03-09 18:00
Done
