### ISSUE TITLE
POST-PROMD: an open-source POST-PROcessing software for Molecular Dynamics simulations

### ISSUE THREAD

**Issue by ghost** [ReScience/submissions#83] opened 2024-04-17 19:14 UTC

**Comment by ghost** [comment] 2024-04-17 19:18
Dear Konrad Hinsen,
Regarding your email, I have corrected the issues and prepared the manuscript according to 
Rescience C latex template. Sorry for the delay and thank you for your attention.
--
Best regards,
[Ashkan Shekaari](https://rt.academia.edu/AshkanShekaari)

**Comment by ghost** [comment] 2024-04-17 19:24
#### Also, this work contributes to "computational physics".

**Comment by khinsen** [comment] 2024-04-18 13:36
I understand the relation to computational physics. But ReScience is primarily about replications of published computational studies, and secondarily accepts reproduction reports if they contain something of interest. Your paper looks like it's about a piece of software. Did you consider submitting to [JOSS](https://joss.theoj.org/), the Journal of Open Source Software?

**Comment by ghost** [comment] 2024-04-18 13:44
Yes, I am!

--
All the best,
Ashkan Shekaari (Lab in Lap)

**Comment by khinsen** [comment] 2024-04-25 07:19
@ReScience/editors I consider this submission out of scope of ReScience C, for describing neither a replication nor a reproduction attempt. If anyone disagrees, please speak up!

**Comment by oliviaguest** [comment] 2024-04-25 07:23
Yes, indeed, perhaps they want to submit it to JOSS, but that is not for us to say as I am not sure of if they meet those criteria either of course (I have not checked closely enough).

**Comment by rougier** [comment] 2024-04-29 12:27
Out of scope for the journal ReScience C

**Closed as completed by rougier** 2024-04-29 12:27 UTC
